#spring.application.name=chap03-spring-security-lecture-source
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs
    username: swcamp
    password: swcamp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.springsecurity.query.dto
jwt:
  secret: XV9XKtlKfqQv0cnSyFYL6QJ0a4e7gST/3WHE2sawDuXQjnjxEivMCb/+d1UeTFw2MEXXYtcdizExjEYD2sDi5A==
  expiration: 1800000 # 30분 (access token)
  refresh-expiration: 604800000 # 7일 (refresh token)