spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: root
    password: root
  jpa:
    show-sql: true # ??? sql??? ??
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true